### ISSUE TITLE
Add Community Health Files

### ISSUE THREAD

**Issue by RileyKenyon** [ad3154/ISO11783-CAN-Stack#101]
I see you already have the `CODE_OF_CONDUCT` - may be worthwhile adding additional items such as `CONTRIBUTING` and templates for feature requests / bug reports.

For reference:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by ad3154** [comment]
I have proposed a contributing document in #104 for your review, as well as @GwnDaan who I think asked for the debugger instructions initially.
