### ISSUE TITLE
Add support for Inno-Maker USB2CAN

### ISSUE THREAD

**Issue by ad3154** [ad3154/ISO11783-CAN-Stack#134]
I have an inno-maker USB2CAN that has an open source driver here https://github.com/INNO-MAKER/usb2can

This adapter has a native Linux driver (Socket CAN) but it would be fairly trivial to add support for Windows, which would be convenient given the adapter's low cost. Can maybe also add MacOS but I do not have a Mac to test on, so we would need someone to help test that if we add it.

**Comment by GwnDaan** [comment]
Oeh nice, I see you already started on this. I just got myself this little guy.

![20230126_184419.jpg](https://user-images.githubusercontent.com/29043784/214910034-168469c7-5a55-4e20-aa53-74f33d7efc73.jpg)

**Comment by GwnDaan** [comment]
Hmm, I can take over the development of this if you like? I have some extra free time this weekend and I'm curious to see this thing in action.

**Comment by ad3154** [comment]
Sure, I'd appreciate it
