### ISSUE TITLE
Adding an external tool for possibly cleaner code

### ISSUE THREAD

**Issue by GwnDaan** [ad3154/ISO11783-CAN-Stack#151]
I'm not really sure what these integrations are called, but would something like [sonarcloud](https://www.sonarsource.com/products/sonarcloud/) or [codecov](https://about.codecov.io/) be something we want to integrate to analyze the overal project? From what I see their service offers automatic code coverage analyses and code feedback, but I haven't used anything like this before, so I'm curious what your opinions are on this.

**Comment by ad3154** [comment]
Though, like I said, 150/yr isn't super terrible. We could maybe spin up a free trial on my web server and see if we like it?

**Comment by GwnDaan** [comment]
> SonarCloud doesn't list C++ though in its free tier

I think you are looking at SonarCube instead of SonarCloud there? [This ](https://community.sonarsource.com/t/sonarcloud-vs-sonarqube/9557/2)might help to understand the differences? Seems like SonarCube is more for businesses and SonarCloud for cloud solutions, like open-source projects?

**Comment by ad3154** [comment]
Oh snap, you're right! Well, sweet! We should give it a try!

**Comment by GwnDaan** [comment]
Sounds good! I'm curious what it will say about our code haha
