### ISSUE TITLE
Query using library

### ISSUE THREAD

**Issue by acode-x** [ad3154/ISO11783-CAN-Stack#168]
Hi,

I wish to write an application which reads messages by broadcast or requests/response in a J1939 network. Unfortunately my environment only has 4.14.X kernel version, hence no J1939 kernel modules.
Can I use this library to achieve the same?
Requesting your thoughts on above.

Thanks

**Comment by ad3154** [comment]
Hello! Thanks for your question.

Our library handles J1939 communication in user space and does not need the J1939 kernel modules to function, so this library should work for you even on your older kernel version!

**Comment by acode-x** [comment]
Thanks @ad3154
