### ISSUE TITLE
Uniform use of British/American English in variable names (color/colour)

### ISSUE THREAD

**Issue by tomstix** [ad3154/ISO11783-CAN-Stack#170]
I noticed that in the Virtual Terminal Client source code, there is inconsistent use of the word color/colour. I think we should keep an eye on keeping naming things like this consistent.
For example:
https://github.com/ad3154/ISO11783-CAN-Stack/blob/5a9b0c92e8060d34d2bd0be78d45700f52f5cee0/isobus/src/isobus_virtual_terminal_client.cpp#L482-L498
My proposal for this particular case is to use colour, as this is also what's used in ISO11783.
What are your opinions on this?

**Comment by ad3154** [comment]
My preference is to use `colour` universally since that's what is used in the ISO docs

**Comment by ad3154** [comment]
Addressed in #172
