### ISSUE TITLE
Add documentation of CANStackLogger usage

### ISSUE THREAD

**Issue by GwnDaan** [ad3154/ISO11783-CAN-Stack#70]
I couldn't find any concrete implementation of CANStackLogger in the tutorials/examples. We could consider adding it to the existing examples. Also displaying the error/warning messages by default for the VT example could be important for unexperienced users testing this library.

**Comment by ad3154** [comment]
This is a bug stemming from the issue that the function signature for `get_can_stack_logger` is `bool CANStackLogger::get_can_stack_logger(CANStackLogger *canStackLogger)` but should be `bool CANStackLogger::get_can_stack_logger(CANStackLogger *&canStackLogger)` (note the missing & 🙄)

**Comment by ad3154** [comment]
Added a fix and documentation to this PR for your review @GwnDaan #74
