### ISSUE TITLE
N2K FP should not be successfully sending messages with interface down

### ISSUE THREAD

**Issue by GwnDaan** [ad3154/ISO11783-CAN-Stack#75]
![image](https://user-images.githubusercontent.com/29043784/207967853-159ad8af-c04f-41b8-898b-f472bf0733ad.png)

I would've liked to find the root cause of this issue myself, but I find it a bit tedious to put debug logs everywhere till I find the root of the issue. Surely there has to be a better way to debug this by being able to use breakpoints or something?

**Comment by ad3154** [comment]
Yes, I usually debug using VS Code with breakpoints and all that. I can write up some instructions and add them to a contributing file to help get you going
